---
collections:
  # https://github.com/ansible-collections/community.general
  - name: community.general
    version: 10.1.0
  # https://github.com/containers/ansible-podman-collections
  - name: containers.podman
    version: 1.16.2
