---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if pipx is installed
      ansible.builtin.package:
        name: pipx
        state: present
      check_mode: true
      register: pkg

    - name: Fail if package was not installed
      ansible.builtin.assert:
        that:
          - pkg.changed is false
        fail_msg: "Package pipx was not installed!"
        success_msg: "Package pipx was installed."
