---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Create group test
      ansible.builtin.group:
        name: grouptest
        state: present

    - name: Create user test
      ansible.builtin.user:
        name: usertest
        group: grouptest
        shell: /bin/bash
        state: present

    - name: Ensure apt cache is updated and required packages are present
      ansible.builtin.apt:
        name:
          - bash-completion
        state: present
        update_cache: true
      when: ansible_pkg_mgr == 'apt'
